# -*- coding: utf-8 -*-
"""Fetch_Job_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAR-Ot1FKQdNojgelsFnY2vXKAD09iYy
"""

import requests
import pandas as pd
import smtplib
from email.message import EmailMessage
import schedule
import time

# ------------------------ JOB SCRAPING FUNCTION ------------------------
def fetch_jobs():
    url = "https://indeed-scraper-api.p.rapidapi.com/api/job"
    locations = ["Taguig"]
    all_jobs = []

    for loc in locations:
        payload = {
            "scraper": {
                "maxRows": 5,
                "query": "Data Science",
                "location": loc,
                "jobType": "internship",
                "radius": "50",
                "sort": "relevance",
                "fromDays": "7",
                "country": "ph"
            }
        }

        headers = {
            "x-rapidapi-key": "ENTER API KEY",
            "x-rapidapi-host": "indeed-scraper-api.p.rapidapi.com",
            "Content-Type": "application/json"
        }

        response = requests.post(url, json=payload, headers=headers)
        jobs_data = response.json()
        job_list = jobs_data.get('returnvalue', {}).get('data', [])

        for job in job_list:
            job_info = {
                "Title": job.get("title", ""),
                "Company": job.get("companyName", ""),
                "City": job.get("location", {}).get("city", ""),
                "Job Type": ", ".join(job.get("jobType", [])),
                "Description": job.get("descriptionText", "")[:300] + "...",
                "Job URL": job.get("jobUrl", "")
            }
            all_jobs.append(job_info)

    # Convert to DataFrame and save as Excel
    df = pd.DataFrame(all_jobs)
    df.to_csv("jobs.csv", index=False)
    print("Jobs saved to cvc.")
    print(df)
    return "jobs.csv"

# ------------------------ EMAIL FUNCTION ------------------------
def send_email(file_path):
    EMAIL_ADDRESS = "EMAIL"        # Replace with your email
    EMAIL_PASSWORD = "PASSWORD"          # Use app password if Gmail

    msg = EmailMessage()
    msg['Subject'] = 'Latest Data Science Jobs'
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = "mickulms.7@gmail.com"       # Your email or another recipient
    msg.set_content("Hi, \n\nPlease find attached the latest Data Science internship jobs.\n\nBest regards!")

    # Attach the Excel file
    with open(file_path, 'rb') as f:
        file_data = f.read()
        file_name = f.name
    msg.add_attachment(file_data, maintype='application', subtype='vnd.openxmlformats-officedocument.spreadsheetml.sheet', filename=file_name)

    # Send email via SMTP
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        smtp.send_message(msg)
    print("Email sent successfully!")

# ------------------------ SCHEDULE EVERY 5 DAYS ------------------------
def job_pipeline():
    csv_file_path = fetch_jobs()
    send_email(csv_file_path)

# Run every 5 days
schedule.every().days.do(job_pipeline)

print("Scheduler running... Press Ctrl+C to stop.")
while True:
    schedule.run_pending()
    time.sleep(60)



